before_install:
  - brew update
  - brew unlink xctool
  - brew install xctool --HEAD
language: objective-c
xcode_workspace: Stripe.xcworkspace
xcode_scheme: StripeiOSExcludingFunctionalTests
xcode_sdk: iphonesimulator