language: objective-c
before_install: gem install xcpretty --no-ri --no-rdoc
script: xcodebuild -workspace Stripe.xcworkspace -scheme StripeiOS -sdk iphonesimulator build test | xcpretty -c && exit ${PIPESTATUS[0]}