language: objective-c
osx_image: xcode7.3
env:
  matrix:
  - TEST_TYPE=lint
  - TEST_TYPE=tests
  - TEST_TYPE=installation
  global:
    secure: gZMOaHQIeG7nplBCuH7EKf9o6Ez2rtoSskrv3nOTziSxFfZq322MrxvkidDpEN7AKWYQm27FO+tCzgq0slXb578lQ9P5ySDwEdExKtk/jMtKsBsf3cr4dzSMiqV5D5TbsH2jE9HQlpYUoJeoMBicR2XsTmd7wiu2jAzNBFqGfiY=

before_install:
- SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 6 (9.3) \[.*\]" | grep -o
  "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")
script:
- open -a "simulator" --args -CurrentDeviceUDID $SIMULATOR_ID
- "./ci_scripts/check_version.rb"
- '[ "$TEST_TYPE" != lint ] || ./ci_scripts/check_fauxpas.sh'
- '[ "$TEST_TYPE" != tests ] || ./ci_scripts/run_tests.sh'
- '[ "$TEST_TYPE" != installation ] || ./ci_scripts/run_installation_tests.sh'
